=== maxwuestehube/xmlpraktikum/mancala/3_xslt/MancalaGame.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT MancalaGame (Player, Player, PlayerOnTurn) >

<!ELEMENT Player (Name, WinCount, PlayersHalf, SeedCount)>
<!ELEMENT Name (#PCDATA) >
<!ELEMENT WinCount (#PCDATA) >
<!ELEMENT SeedCount (#PCDATA) >

<!ELEMENT PlayersHalf (Kalah, House, House, House, House, House, House) >
<!ELEMENT Kalah (SeedCount)>
<!ELEMENT House (SeedCount)>

<!ELEMENT PlayerOnTurn (#PCDATA) >

=== maxwuestehube/xmlpraktikum/mancala/3_xslt/Game States/Game State 2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MancalaGame SYSTEM "../MancalaGame.dtd">
<MancalaGame>
    <Player>
        <Name>abc</Name>
        <WinCount>1</WinCount>
        <PlayersHalf>
            <Kalah>
                <SeedCount>10</SeedCount>
            </Kalah>
            <House>
                <SeedCount>2</SeedCount>
            </House>
            <House>
                <SeedCount>3</SeedCount>
            </House>
            <House>
                <SeedCount>4</SeedCount>
            </House>
            <House>
                <SeedCount>1</SeedCount>
            </House>
            <House>
                <SeedCount>6</SeedCount>
            </House>
            <House>
                <SeedCount>10</SeedCount>
            </House>
        </PlayersHalf>
        <SeedCount>36</SeedCount>
    </Player>
    <Player>
        <Name>xyz</Name>
        <WinCount>2</WinCount>
        <PlayersHalf>
            <Kalah>
                <SeedCount>8</SeedCount>
            </Kalah>
            <House>
                <SeedCount>8</SeedCount>
            </House>
            <House>
                <SeedCount>10</SeedCount>
            </House>
            <House>
                <SeedCount>4</SeedCount>
            </House>
            <House>
                <SeedCount>1</SeedCount>
            </House>
            <House>
                <SeedCount>3</SeedCount>
            </House>
            <House>
                <SeedCount>2</SeedCount>
            </House>
        </PlayersHalf>
        <SeedCount>36</SeedCount>
    </Player>
    <PlayerOnTurn>abc</PlayerOnTurn>
</MancalaGame>

=== maxwuestehube/xmlpraktikum/3_xslt/Game States/Game State 3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MancalaGame SYSTEM "../MancalaGame.dtd">
<MancalaGame>
    <Player>
        <Name>Player1</Name>
        <WinCount>5</WinCount>
        <PlayersHalf>
            <Kalah>
                <SeedCount>10</SeedCount>
            </Kalah>
            <House>
                <SeedCount>3</SeedCount>
            </House>
            <House>
                <SeedCount>3</SeedCount>
            </House>
            <House>
                <SeedCount>4</SeedCount>
            </House>
            <House>
                <SeedCount>1</SeedCount>
            </House>
            <House>
                <SeedCount>6</SeedCount>
            </House>
            <House>
                <SeedCount>3</SeedCount>
            </House>
        </PlayersHalf>
        <SeedCount>6</SeedCount>
    </Player>
    <Player>
        <Name>Player2</Name>
        <WinCount>13</WinCount>
        <PlayersHalf>
            <Kalah>
                <SeedCount>8</SeedCount>
            </Kalah>
            <House>
                <SeedCount>8</SeedCount>
            </House>
            <House>
                <SeedCount>10</SeedCount>
            </House>
            <House>
                <SeedCount>4</SeedCount>
            </House>
            <House>
                <SeedCount>1</SeedCount>
            </House>
            <House>
                <SeedCount>2</SeedCount>
            </House>
            <House>
                <SeedCount>1</SeedCount>
            </House>
        </PlayersHalf>
        <SeedCount>2</SeedCount>
    </Player>
    <PlayerOnTurn>Player1</PlayerOnTurn>
</MancalaGame>
