=== maxwuestehube/xmlpraktikum/mancala/Uebungsblatt3/MancalaDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Mancalaboard (Spieler, Spieler) >

<!ELEMENT Spieler (Name, AnzGewinne, IstAmZug, AnzSteine, Spielfeld)>

<!ELEMENT Name (#PCDATA) >
<!ELEMENT AnzGewinne (#PCDATA) >
<!ELEMENT IstAmZug (#PCDATA) >
<!ELEMENT AnzSteine (#PCDATA) >
<!ELEMENT Spielfeld (Mulde, (Mulde)+) >

<!ELEMENT Mulde (AnzSteine, Mulde)>

=== maxwuestehube/xmlpraktikum/mancala/Uebungsblatt3/Mancala.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Spieler SYSTEM "MancalaDTD.dtd">
<Spieler>
    <Name>  </Name>
    <AnzGewinne> 5 </AnzGewinne>
    <IstAmZug> </IstAmZug>
    <AnzSteine> </AnzSteine>
    <Spielfeld>
        <Mulde>
            <AnzSteine> </AnzSteine>
        </Mulde>
        <Mulde>
            <AnzSteine> </AnzSteine>
        </Mulde>
    </Spielfeld>
</Spieler>

=== maxwuestehube/xmlpraktikum/mancala/Uebungsblatt3/Mancala1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mancalaboard SYSTEM "MancalaDTD.dtd">
<Mancalaboard>
    <Spieler>
        <Name>Spieler1</Name>
        <AnzGewinne>5</AnzGewinne>
        <IstAmZug>Spieler1</IstAmZug>
        <AnzSteine>36</AnzSteine>
        <Spielfeld>
            <Kalaha>
                <AnzSteine>6</AnzSteine>
            </Kalaha>
            <Mulde>
                <AnzSteine>8</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>5</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>3</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>2</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>8</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>4</AnzSteine>
            </Mulde>
        </Spielfeld>
    </Spieler>
    <Spieler>
        <Name>Spieler2</Name>
        <AnzGewinne>5</AnzGewinne>
        <IstAmZug>Spieler2</IstAmZug>
        <AnzSteine>36</AnzSteine>
        <Spielfeld>
            <Kalaha>
                <AnzSteine>7</AnzSteine>
            </Kalaha>
            <Mulde>
                <AnzSteine>8</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>3</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>6</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>6</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>6</AnzSteine>
            </Mulde>
            <Mulde>
                <AnzSteine>0</AnzSteine>
            </Mulde>
        </Spielfeld>
    </Spieler>
</Mancalaboard>

=== maxwuestehube/xmlpraktikum/mancala/Uebungsblatt3/Mancala3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mancalaboard SYSTEM "MancalaDTD.dtd">
<Mancalaboard>
    <Spieler>
        <Name></Name>
        <AnzGewinne></AnzGewinne>
        <IstAmZug></IstAmZug>
        <AnzSteine></AnzSteine>
        <Spielfeld>
            <Kalaha>
                <AnzSteine></AnzSteine>
            </Kalaha>
            <Mulde>
                <AnzSteine></AnzSteine>
            </Mulde>
        </Spielfeld>
    </Spieler>
    <Spieler>
        <Name></Name>
        <AnzGewinne></AnzGewinne>
        <IstAmZug></IstAmZug>
        <AnzSteine></AnzSteine>
        <Spielfeld>
            <Kalaha>
                <AnzSteine></AnzSteine>
            </Kalaha>
            <Mulde>
                <AnzSteine></AnzSteine>
            </Mulde>
        </Spielfeld>
    </Spieler>
</Mancalaboard>
